import React from 'react';

const TermsAndConditions = () => {
    return (
        <div className="terms-conditions-container" style={{ padding: '20px', fontFamily: 'Arial, sans-serif', lineHeight: '1.6' }}>
            <h1 style={{ textAlign: 'center', marginBottom: '20px' }}>Terms and Conditions</h1>

            <h2>Shipping Policy for Tara Collection</h2> <br/>
            

            <p>At <strong>Tara Collection</strong>, we strive to provide a seamless shopping experience for our customers. This Shipping Policy outlines how we handle the delivery of our artificial jewelry products.</p>

            <h3>1. Order Processing Time</h3>
            <ul>
                <li>Orders are processed within 1-3 business days (excluding weekends and holidays) after payment is received.</li>
                <li>You will receive a confirmation email with your order details once your order is placed successfully.</li>
            </ul> <br/>

            <h3>2. Shipping Methods and Delivery Times</h3>
            <p>We offer the following shipping options:</p>
            <ul>
                <li><strong>Standard Shipping:</strong> Delivery within 5-7 business days.</li>
                <li><strong>Express Shipping:</strong> Delivery within 2-4 business days.</li>
            </ul><br/>
            <p>Delivery times may vary based on your location and external factors such as weather or courier delays.</p> <br/>

            {/* <h3>3. Shipping Charges</h3>
            <ul>
                <li>Shipping charges are calculated at checkout based on the delivery address and chosen shipping method.</li>
                <li>Free shipping is available on orders above [Insert Free Shipping Threshold Amount].</li>
            </ul><br/>

            <h3>4. Tracking Your Order</h3>
            <ul>
                <li>Once your order is shipped, you will receive an email with the tracking number and instructions to track your shipment.</li>
                <li>You can also track your order directly through our website under the "Order Tracking" section.</li>
            </ul><br/>

            <h3>5. International Shipping</h3>
            <ul>
                <li>We currently [do/do not] offer international shipping. If available, international shipping times and costs will be displayed at checkout.</li>
                <li>International orders may be subject to customs duties or taxes, which are the responsibility of the customer.</li>
            </ul><br/>

            <h3>6. Shipping Address</h3>
            <p>Ensure that your shipping address is accurate and complete at checkout. We are not responsible for delayed or failed deliveries due to incorrect addresses.</p><br/>

            <h3>7. Lost or Damaged Shipments</h3>
            <ul>
                <li>If your shipment is lost or damaged in transit, please contact us immediately at [taracollection766@gmail.com || +91-8824454873].</li>
                <li>We will work with the courier service to resolve the issue and provide a replacement or refund if applicable.</li>
            </ul><br/> */}

            <p>Terms &amp; Conditions


This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://taracollection.in/ ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').

The Platform is owned by TARA COLLECTION, a company incorporated under the Companies Act, 1956 with its registered office at  (hereinafter referred to as ?Platform Owner?, 'we', 'us', 'our')..

Your use of the Platform and services and tools are governed by the following terms and conditions (?Terms of Use?) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services'). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates..

 For the purpose of these Terms of Use, wherever the context so requires ?you?, 'your' or ?user? shall mean any natural or legal person who has agreed to become a user/buyer on the Platform..

ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING..

The use of Platform and/or availing of our Services is subject to the following Terms of Use:

To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform..

Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law..

Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements..

The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics..

You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws..

You agree to pay us the charges associated with availing the Services..

You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.

You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information..

You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services..

You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.

Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event..

These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India..

All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website
</p>
<h3>3. Return Policy</h3>
            <ul>
                <li>Items can be returned within 3 days of delivery if they are unused, unworn, and in their original packaging with tags intact.</li>
                <li>If refund approved money it will be credited in account within 7days.</li>
                {/* <li>The customer is responsible for return shipping costs unless the return is due to a defect or error on our part.</li>
                <li>Once the returned item is received and inspected, we will notify you of the approval or rejection of your return.</li> */}
            </ul><br/>

 </div>
    );
};

export default TermsAndConditions;
